# Generated by Django 3.2.7 on 2021-09-23 14:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=80, unique=True, verbose_name='Name')),
                ('address', models.TextField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid Phone number.', regex='^[6789]\\d{9}$')], verbose_name='Phone')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last Login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_covid_beds', models.IntegerField(blank=True, null=True)),
                ('v_covid_beds', models.IntegerField(blank=True, null=True)),
                ('o_covid_beds', models.IntegerField(blank=True, null=True)),
                ('t_ventilators', models.IntegerField(blank=True, null=True)),
                ('v_ventilators', models.IntegerField(blank=True, null=True)),
                ('o_ventilators', models.IntegerField(blank=True, null=True)),
                ('t_icu_beds', models.IntegerField(blank=True, null=True)),
                ('v_icu_beds', models.IntegerField(blank=True, null=True)),
                ('o_icu_beds', models.IntegerField(blank=True, null=True)),
                ('t_oxygen_beds', models.IntegerField(blank=True, null=True)),
                ('v_oxygen_beds', models.IntegerField(blank=True, null=True)),
                ('o_oxygen_beds', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
